### ISSUE TITLE
Nameservers please remove omitempty

### ISSUE THREAD

**Issue by idefixcert** [mittwald/go-powerdns#4]
Could you please remove the omit empty in the zone nameservers.
Problem is that powerdns api needs a this array, even if it is empty.

https://github.com/mittwald/go-powerdns/blob/74bf60e771b9fcb4dc98d84f7f7eb017c42403c9/apis/zones/types_zone.go#L22

**Comment by martin-helmich** [comment]
Thanks for the hint! Fixed in #5. :+1:

**Comment by idefixcert** [comment]
Thanx for the fix, wait for the next release.

**Comment by martin-helmich** [comment]
v0.2.3 was tagged just now. Enjoy! 😉👍

**Comment by idefixcert** [comment]
Sorry, I think that made the problem even worse.
So in each patch we have the nameserver: null in it, and this is also not right.
So I think we should just set it back to the original codebase.

Sorry.

**Comment by martin-helmich** [comment]
Thanks for the feedback! I've provided an alternative solution in #6 which should enforce that `nameservers` is always an (albeit empty) array.
